### ISSUE TITLE
Installed version incompatible with Meccano testnet

### ISSUE THREAD

**Issue by phillux** [totem-tech/totem-meccano-node#1]
I followed the instructions according to the Readme, but after launching and connecting to 0 peers, I noticed on telemetry that my node is running 1.1.9, while all others are running 1.1.8.

since there are no tags or releases i can point to in this repo, how can i download the correct version in order to connect to the testnet?

**Comment by chrisdcosta** [comment]
@phillux yeah sorry about this, you caught us in between the upgrade which should be happening today. 

The network is still on 1.1.8 and the upgrade transaction hasn't been executed.

We had issues with the last upgrade where the network went out of sync, so this time we are just taking it step by step. I will post back here when it's done.

**Comment by chrisdcosta** [comment]
@phillux upgrade is complete. You should be able to sync with the network now. We have some nodes running 1.1.8 (upgraded by transaction to 1.1.9) and some running the full node at 1.1.9

All are syncing blocks and finalisation is happening. 

As far as a release repo, we have a [binaries repo in Gitlab](https://gitlab.com/totem-tech/totem-meccano-binaries)... I will mirror it here.

**Comment by chrisdcosta** [comment]
@phillux should also mention we have a Public [Discord](https://discord.gg/nMPPmtm). I see you joined, but it's still not syncing. Can discuss there.

**Comment by chrisdcosta** [comment]
@phillux OK I've looked into this. There is an issue starting the node from at the current version `1.1.9` if it's compiled from source, and it has not been run before. I also see the same issues when running the binaries version `1.1.8` and `1.1.9` if version `1.1.6` was never run.

That said the workaround is to execute the binary version `1.1.6` even for a short time, before starting any later version. They should share the same data directory (on linux `.local/share/totem-meccano`) which you could remove completely to reset everything before restarting on `v1.1.6`. 

I will post the workaround into discord for the time being.

**Comment by chrisdcosta** [comment]
@phillux we posted a fix to the issue. 

Could you pull the latest master ( f033f089cd87bc7985572406ecb3216ded6f8ab4 ) & recompile. You will also need to delete the existing data in the totem-meccano data directory (`.local/share/totem-meccano` on linux distros) to get a clean start. 

If this is fixed please let me know and I can close the issue.

**Comment by chrisdcosta** [comment]
Confirmed as fixed. Closing.
